const nodemailer = require("nodemailer");

/**
 * Sends a welcome email containing login credentials.
 * @param {string} toEmail 
 * @param {string} name 
 * @param {string} role 
 * @param {string} rawPassword 
 */
const sendWelcomeEmail = async (toEmail, name, role, rawPassword) => {
  try {
    // Attempt configuration from ENV. Provide fallback for debugging/silently passing if no ENV provided.
    const transporter = nodemailer.createTransport({
      host: process.env.EMAIL_HOST || "smtp.gmail.com",
      port: process.env.EMAIL_PORT || 465,
      secure: true, // Use SSL/TLS
      auth: {
        user: process.env.EMAIL_USER,
        pass: process.env.EMAIL_PASS
      }
    });

    const loginUrl = "http://localhost:5173/";

    // Construct the HTML Email
    const htmlContent = `
      <div style="font-family: Arial, sans-serif; background-color: #f4f4f9; padding: 20px;">
        <div style="max-w-width: 600px; margin: 0 auto; background-color: #ffffff; padding: 30px; border-radius: 8px; box-shadow: 0 4px 6px rgba(0,0,0,0.1);">
          <h2 style="color: #4F46E5; text-align: center;">Welcome to HR WorkSphere!</h2>
          <p style="color: #333333; font-size: 16px;">Hi <strong>${name}</strong>,</p>
          <p style="color: #333333; font-size: 16px;">Your <strong>${role}</strong> profile has been successfully created by Human Resources. You can now log into your dashboard using the credentials below.</p>
          
          <div style="background-color: #F9FAFB; padding: 15px; border-left: 4px solid #4F46E5; margin: 20px 0; border-radius: 4px;">
            <p style="margin: 0 0 10px 0; font-size: 14px;"><strong>Email (Username):</strong> ${toEmail}</p>
            <p style="margin: 0; font-size: 14px;"><strong>Temporary Password:</strong> <span style="font-family: monospace; background-color: #e5e7eb; padding: 2px 6px; border-radius: 4px;">${rawPassword}</span></p>
          </div>

          <p style="color: #EF4444; font-size: 14px;"><em>* For security reasons, please log in and change your password as soon as possible.</em></p>

          <div style="text-align: center; margin-top: 30px;">
            <a href="${loginUrl}" style="background-color: #4F46E5; color: #ffffff; padding: 12px 24px; text-decoration: none; border-radius: 6px; font-weight: bold; display: inline-block;">Log In & Reset Password</a>
          </div>
          
          <hr style="border: none; border-top: 1px solid #E5E7EB; margin-top: 30px; margin-bottom: 20px;" />
          <p style="color: #9CA3AF; font-size: 12px; text-align: center;">This is an automated message generated by the HR system.</p>
        </div>
      </div>
    `;

    const mailOptions = {
      from: `"HR Department" <${process.env.EMAIL_USER || "hr@worksphere.com"}>`,
      to: toEmail,
      subject: "Welcome to HR WorkSphere - Your Login Credentials",
      html: htmlContent
    };

    // Only send if the credentials are set, else just log it out.
    if (process.env.EMAIL_USER && process.env.EMAIL_PASS) {
      await transporter.sendMail(mailOptions);
      console.log(`✅ Welcome email sent to ${toEmail}`);
    } else {
      console.log("⚠️ EMAIL_USER not configured in backend/.env. Mail intercepted: ", mailOptions);
    }
    
  } catch (err) {
    console.error("❌ Error sending welcome email:", err);
  }
};

module.exports = { sendWelcomeEmail };
